operatorid: POLIBA
networkelementid: openli-lab
interceptpointid: col001

encoderthreads: 2

inputs:
  - uri: eth2
    threads: 2
    hasher: radius
    #filter:

etsitls: no

provisioneraddr: 172.19.0.3
provisionerport: 9001

RMQenabled: false
#RMQname: "RMQNAME"
#RMQpass: "RMQPASSWORD"

#tlscert: <TLSCERT>
#tlskey: <TLSKEY>
#tlsca: <TLSCA>

#alumirrors: []
#jmirrors: []